name: CI

on:
  push:
    branches: [ master ]

jobs:
  find:
    name: Setup repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ajuvercr/markdown-templates@v1
        with:
          paper: sds-demo
      - uses: peaceiris/actions-gh-pages@v3
        with:
          target_branch: gh-pages
          publish_dir: ./out
          github_token: ${{ secrets.GITHUB_TOKEN }}

